// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test, Vm} from "forge-std/Test.sol";
import {SealedDAO} from "../../src/SealedDAO.sol";

/// @notice PRD 8.1 "FFI": SealedDAO.hashVote, the committed vectors (test/vectors/hashvote.json, generated by the SDK)
///         and the built SDK itself (packages/sdk/scripts/ffi-hash-vote.mjs via vm.ffi) must agree.
/// @dev Needs `ffi = true` (foundry.toml) and a built SDK: `pnpm --filter @arcseal/sdk build`. The root `pnpm test`,
///      `pnpm check` and `pnpm contracts:test:ci` build it first.
contract HashVoteFfiTest is Test {
    string internal constant VECTORS = "test/vectors/hashvote.json";
    string internal constant SDK_SCRIPT = "../packages/sdk/scripts/ffi-hash-vote.mjs";
    uint256 internal constant VECTOR_COUNT = 10;

    struct Vector {
        uint256 proposalId;
        address voter;
        uint8 choice;
        bytes32 salt;
        bytes32 commitment;
    }

    SealedDAO internal dao;
    string internal json;

    function setUp() public {
        address[] memory members = new address[](1);
        members[0] = address(this);
        // hashVote is pure: the token address only has to be non-zero
        dao = new SealedDAO(address(0xdead), members, 5000, 0);
        json = vm.readFile(VECTORS);
    }

    function _vector(uint256 i) internal view returns (Vector memory v) {
        string memory at = string.concat(".vectors[", vm.toString(i), "]");
        v.proposalId = vm.parseJsonUint(json, string.concat(at, ".proposalId"));
        v.voter = vm.parseJsonAddress(json, string.concat(at, ".voter"));
        // casting to 'uint8' is safe because the vectors hold choices 0..2 (and Choice(v.choice) would revert otherwise)
        // forge-lint: disable-next-line(unsafe-typecast)
        v.choice = uint8(vm.parseJsonUint(json, string.concat(at, ".choice")));
        v.salt = vm.parseJsonBytes32(json, string.concat(at, ".salt"));
        v.commitment = vm.parseJsonBytes32(json, string.concat(at, ".commitment"));
    }

    /// @dev hashVote computed by the built SDK in a node subprocess.
    function _sdkHashVote(uint256 id, address voter, uint8 choice, bytes32 salt) internal returns (bytes32) {
        string[] memory cmd = new string[](6);
        cmd[0] = "node";
        cmd[1] = SDK_SCRIPT;
        cmd[2] = vm.toString(id);
        cmd[3] = vm.toString(voter);
        cmd[4] = vm.toString(uint256(choice));
        cmd[5] = vm.toString(salt);
        Vm.FfiResult memory r = vm.tryFfi(cmd);
        assertEq(r.exitCode, 0, string.concat("ffi-hash-vote failed (build the SDK first): ", string(r.stderr)));
        assertEq(r.stdout.length, 32, "ffi-hash-vote must print exactly 32 bytes");
        return bytes32(r.stdout);
    }

    function test_ffi_vectorsHaveTenEntries() public view {
        assertTrue(vm.keyExistsJson(json, string.concat(".vectors[", vm.toString(VECTOR_COUNT - 1), "]")));
        assertFalse(vm.keyExistsJson(json, string.concat(".vectors[", vm.toString(VECTOR_COUNT), "]")));
    }

    function test_ffi_contractMatchesCommittedVectors() public view {
        for (uint256 i; i < VECTOR_COUNT; ++i) {
            Vector memory v = _vector(i);
            assertEq(
                dao.hashVote(v.proposalId, v.voter, SealedDAO.Choice(v.choice), v.salt),
                v.commitment,
                string.concat("vector ", vm.toString(i))
            );
        }
    }

    function test_ffi_sdkMatchesContractOnVectors() public {
        for (uint256 i; i < VECTOR_COUNT; ++i) {
            Vector memory v = _vector(i);
            bytes32 sdk = _sdkHashVote(v.proposalId, v.voter, v.choice, v.salt);
            assertEq(sdk, v.commitment, string.concat("sdk, vector ", vm.toString(i)));
            assertEq(sdk, dao.hashVote(v.proposalId, v.voter, SealedDAO.Choice(v.choice), v.salt));
        }
    }

    /// @dev Inputs outside the committed file, so a regenerated-but-wrong vector file cannot hide a mismatch.
    function test_ffi_sdkMatchesContractOnFreshInputs() public {
        for (uint256 i; i < 3; ++i) {
            bytes32 r = keccak256(abi.encode("arcseal.ffi.fresh", i));
            uint256 id = uint256(r) >> (64 * i);
            address voter = address(uint160(uint256(keccak256(abi.encode(r)))));
            // casting to 'uint8' is safe because i % 3 < 3
            // forge-lint: disable-next-line(unsafe-typecast)
            uint8 choice = uint8(i % 3);
            bytes32 salt = keccak256(abi.encode(r, "salt"));
            assertEq(_sdkHashVote(id, voter, choice, salt), dao.hashVote(id, voter, SealedDAO.Choice(choice), salt));
        }
    }
}
