// @arcseal/sdk: timelock-sealed votes for SealedDAO on Arc.
export { SEALED_DAO_CREATE2_SALT, sealedDaoAbi, sealedDaoBytecode } from './abi/SealedDAO.js';
export {
  ACTION_KINDS,
  type ActionKind,
  claim,
  execute,
  finalize,
  GAS_MARGIN_PERCENT,
  getProposal,
  getSealedLogs,
  getStatus,
  listProposals,
  MAX_DESCRIPTION_URI_BYTES,
  PROPOSAL_STATUSES,
  type Proposal,
  type ProposalCreated,
  type ProposalStatus,
  type ProposeInput,
  propose,
  proposeInputSchema,
  REVEALED_COMMITMENT,
  type ReadClient,
  readClaimable,
  readCommitmentOf,
  readHashVote,
  readIsMember,
  readMemberCount,
  readProposal,
  readProposalCount,
  readQuorumBps,
  readRevealBounty,
  readRevealOpen,
  readSealingOpen,
  readStatus,
  readTotalClaimable,
  readUsdc,
  revealBatch,
  type SealedBallot,
  type SealedDaoErrorName,
  sealAndVote,
  toContractRevertError,
  vote,
  type WriteClient,
  waitForSuccess,
  withGasMargin,
} from './actions.js';
export {
  DRAND_TIMEOUT_MS,
  DRAND_URLS,
  type DrandBeaconResponse,
  drandBeaconResponseSchema,
  type FetchLike,
  type GetBeaconOptions,
  getBeacon,
  type WaitForRoundOptions,
  waitForRound,
} from './drand.js';
export {
  ArcSealError,
  type ArcSealErrorCode,
  ContractRevertError,
  type DrandAttempt,
  DrandFetchError,
  EventNotFoundError,
  InvalidBeaconError,
  InvalidInputError,
  ProposalNotFoundError,
  TransactionRevertedError,
  WalletRequiredError,
} from './errors.js';
export {
  type CreateLoggerOptions,
  createLogger,
  defaultLogLevel,
  LOG_LEVELS,
  type Logger,
  type LogLevel,
  newCorrelationId,
  withCorrelationId,
} from './logger.js';
export { type BlockWindow, LOG_WINDOW_BLOCKS, type OnWindow, splitBlockRange } from './logs.js';
export { parseVoteReceipt, serializeVoteReceipt } from './receipt.js';
export {
  type BeaconSource,
  buildRevealBatch,
  MAX_REVEAL_BATCH,
  type RevealBatch,
  type RevealItem,
  type SkipReason,
  type UnsealProposalParams,
  type UnsealProposalResult,
  unsealProposal,
} from './reveal.js';
export {
  closeRoundFor,
  EXECUTION_GRACE,
  executionDeadline,
  MAX_VOTING,
  MIN_VOTING,
  pastRevealEnd,
  QUICKNET_GENESIS,
  QUICKNET_PERIOD,
  REVEAL_WINDOW,
  revealEndRoundFor,
  revealOpen,
  roundAfter,
  roundAt,
  roundTime,
  votingOpen,
} from './round.js';
export {
  addressSchema,
  BEACON_SIGNATURE_BYTES,
  type Beacon,
  type BeaconInput,
  beaconSchema,
  beaconSignatureSchema,
  bytes32Schema,
  CHOICES,
  type Choice,
  CIPHERTEXT_MAX_BYTES,
  CIPHERTEXT_MIN_BYTES,
  chainIdSchema,
  choiceSchema,
  ciphertextSchema,
  type HashVoteInput,
  hashVoteInputSchema,
  hexSchema,
  proposalIdSchema,
  type RevealItemInput,
  revealItemSchema,
  roundSchema,
  SALT_BYTES,
  type SealVoteInput,
  saltSchema,
  sealVoteInputSchema,
  type UnsealVoteInput,
  uint256Schema,
  unsealVoteInputSchema,
  type VoteReceipt,
  type VoteReceiptInput,
  voteReceiptSchema,
} from './schemas.js';
export {
  type ChoiceIndex,
  choiceFromIndex,
  choiceToIndex,
  decodeVotePlaintext,
  encodeVotePlaintext,
  generateSalt,
  hashVote,
  type SealedVote,
  sealVote,
  type UnsealVoteOptions,
  unsealVote,
  VOTE_PLAINTEXT_BYTES,
  type VotePlaintext,
} from './seal.js';

/** Arc USDC, ERC-20 view. The native balance is an 18-decimal view of the same funds: never show or sum both. */
export const USDC_ADDRESS = '0x3600000000000000000000000000000000000000' as const;

/** Decimals of the USDC ERC-20 view. Every amount the SDK reads or writes uses this view. */
export const USDC_DECIMALS = 6;
