#!/usr/bin/env node
// Generates the typed SealedDAO module (src/abi/SealedDAO.ts) from the Foundry artifact in contracts/out.
// src/abi/ holds generated files only (biome skips it).
//
//   pnpm contracts:abi                          # forge build + write src/abi/SealedDAO.ts
//   pnpm --filter @arcseal/sdk generate:abi     # write it from the current artifact (run `forge build` first)
//   pnpm --filter @arcseal/sdk check:abi        # exit 1 if the committed module does not match the artifact
//
// --check is strict as soon as either side exists: it fails on a mismatch, on an artifact without a committed
// module, and on a committed module without an artifact. Only when neither exists (before SealedDAO.sol is written)
// does it print a notice and exit 0.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const sdkDir = resolve(here, '..');
const repoDir = resolve(sdkDir, '../..');
const artifactPath = resolve(repoDir, 'contracts/out/SealedDAO.sol/SealedDAO.json');
const modulePath = resolve(sdkDir, 'src/abi/SealedDAO.ts');
const check = process.argv.includes('--check');
const show = (path) => relative(repoDir, path);

const hasArtifact = existsSync(artifactPath);
const hasModule = existsSync(modulePath);

if (!hasArtifact && !hasModule) {
  console.log(`SealedDAO not built yet (no ${show(artifactPath)}, no ${show(modulePath)}): nothing to do`);
  process.exit(0);
}
if (!hasArtifact) {
  console.error(
    `missing ${show(artifactPath)} while ${show(modulePath)} exists; run \`forge build\` in contracts/`,
  );
  process.exit(1);
}

const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'));
const content =
  '// AUTO-GENERATED by packages/sdk/scripts/generate-abi.mjs from contracts/out. Do not edit.\n' +
  '// Regenerate: pnpm contracts:abi\n\n' +
  `export const sealedDaoAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n` +
  '/** Creation bytecode (constructor: usdc, initialMembers, quorumBps, revealBounty). Local anvil tests and CREATE2 checks. */\n' +
  `export const sealedDaoBytecode = '${artifact.bytecode.object}' as const;\n\n` +
  '/** CREATE2 salt label used by contracts/script/Deploy.s.sol: salt = keccak256("arcseal.v1"). */\n' +
  "export const SEALED_DAO_CREATE2_SALT = 'arcseal.v1' as const;\n";

const current = hasModule ? readFileSync(modulePath, 'utf8') : null;
if (current === content) {
  console.log(`${show(modulePath)} is up to date`);
  process.exit(0);
}
if (check) {
  const reason = current === null ? 'is missing' : 'is stale';
  console.error(`${show(modulePath)} ${reason} for ${show(artifactPath)}; run \`pnpm contracts:abi\``);
  process.exit(1);
}
mkdirSync(dirname(modulePath), { recursive: true });
writeFileSync(modulePath, content);
console.log(`wrote ${show(modulePath)}`);
